---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBCsICY9XZWM2sLIF5Q3bIzhrMJsc6T3G4URZZnPv5FB12u5ASnZAP+qQz43elI11aIfQN/hiTbGW60UfgHQtk13bKfJ47CCU2yXSQIEumKHycCWSyh0BL39EgwGc+ZTf5O+MjasxlbxOyg49IDmo5XbiwUhgMqlHr9vAk16Pq5KK9uAmIpcHMd3a29wkL1C2Il2xwApfkP77YKVnF8PgJuve2B7lF/u3exO6a7qLPsDnXWRowekWMoUBhzJ2HnySlk4j0OZj2UI1KkGtqhWZvV2F2uvsyFFnsf1WknbhGeV1nd2yxb7hgOfaG+W7w+gK2lmo90tTScHbXb8am+KpKGZE1Y1c11mfjTi75qihyRX2DnYR7laryr14fnbbp6b2+MZlAW7f9u6Vnan0j5NErADjFstGKdAP6KQlZ0kVx8OYLi2jZDdMib0XN+EKFbwkDS6WEfahHomkyGPvH6riSGwwvBtRK7E7lXd6AeMVlefmXcRHarbArCw38Brl3JukkxhnIViO8s74PUTCzqRhPMeEjJOb0B35wssOfLBxnnJNjD/P+JAB63IpnGlQgus9ok9fqXIl9bY2QS2o4RX7M3XgA9Gtsdy3Tz+LbCED3UAxi1JcxdfaAv+MIcwGGS4jjqWnKM4l/kqNNOciilsGjI9c7+nb0h2oUBIlUdI0GEz43RaPJika4Xd1Rm1p3W+pUlk6BrF+92YgulSmNGsb/x4G8tuIiWYjnKdBBbBYHsCo9dpFyMsUyhqsqTR7CWJEkBikKK3I09hl2o3lNM/7B4EtXdMbbWoPSkaQaEBsFRyUqQFSDpjV46+Re2NOVbj3qKNBgz1JCFU/XK06dQAbSb0T2f+zV45L/LBnlmOY7EcljkUg5XMLVIQM1BGYd65pDcY5KIs5fkrPXR18k1PRkGnD9xV5JKLrIkSk7uvWQ1ZMcqQ0LJ9fq0upyURkOodQNW76GbnIieerDuB9tUH6ZqONN+8YODJMviOx4SnNet/k5OvqSCkVXFPUbgajsc6vJDtdmA5A556Rmx5bAPYNoFXZg+7pVrEt9VuCweUmUwnr3RSybOaPyy8I7JPZK+yVbQQJift4lcYe7lK1+UqU4tschcV84cAh3aSBBWPcvgPDIPcm43fWqHb8t54ZO12I9k6JkHPxStlMGFWOE/WL9m8LlrbQdZfqMSH/Rl1iZ2VRsIRRUHVGSARmuFpdBT+UJd8Zp0xB4iK/bZcCdk6xB0QYo5wAGnu0S1QA38rODOL4YKokGhwkEyhs2HTb6GwjH9KXB0icWme2fZff3vN9kR6Hyd33ZiQNoSJ/71rqaC1tQGMfPr/7NosmyXdOdERARNvXbhT72k/hYNhuh9X9myuFQLjO7CkpIcIoUjLSeuWmaBIQp1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson
